### PR TITLE
Removed linting erros and added a new route

### PR DESCRIPTION
**Pull request by ac030540**
I have made the following changes:

- [x] Added the createProblem route for admin. URL for the same is `localhost:3000/admin/:contestId/create`.

- [x] Removed all the linting errors.

- [x] Added the FileUpload Component.

- [x] Added scripts for linting and accordingly updated CONTRIBUTING.d file.

### CODE REVIEW

**Comment by ac030540** [comment]
@Swap76 you may be seeing this issue because I have changed the way we start the project. The detailed steps can be seen in CONTRIBUTING.md file.

**Comment by Swap76** [comment]
> @Swap76 you may be seeing this issue because I have changed the way we start the project. The detailed steps can be seen in CONTRIBUTING.md file.

@ac030540 Thanks for the help, My bad I haven’t read the contribution.md correctly. Now it’s working perfectly

**Comment by ac030540** [comment]
@Swap76 Thanks :)

**Comment by Mithil467** [comment]
There might be a bug here on http://localhost:3000/admin/:contestId/create. The site crashes.
image
Steps to produce:
1. Click on the upload file option and select any file.
2. Click on the upload file option but this time, do not select any file, and press cancel.

**Comment by ac030540** [comment]
@Mithil467 Thank you for giving your valuable feedback. I will fix it.

**Comment by ac030540** [comment]
> There might be a bug here on http://localhost:3000/admin/:contestId/create. The site crashes.
> image
> Steps to produce:
> 
> 1. Click on the upload file option and select any file.
> 2. Click on the upload file option but this time, do not select any file, and press cancel.

I have fixed it. Let me know if there are any other issues.

**Pull request merged**
