### PR TITLE
UNI04 #24

### PR DESCRIPTION
**Pull request by Ckpuna4**
Add content of Adhoc, Math section on playlist page #24

### CODE REVIEW

**Comment by ac030540** [comment]
Hey @Ckpuna4 Thanks for contributing.

I would request you do the following changes:
Screenshot 2019-10-03 at 1 50 17 AM
- [ ] On my machine the content gets overlapped on footer. This is happening because we have specified a fixed height of 1000px in Sidebar.scss for div.content. You can either increase the height or find a solution to dynamically change the height and avoid overlapping of content with the footer.
Screenshot 2019-10-03 at 1 50 06 AM
- [ ] You should not use the same size for all headings on the page. I would suggest you to reduce the heading size for headings other than the main heading. Also change the colour of those subheadings. Make it back to black. To highlight it you can either increase the font weight or increase the font size (but the font size should be smaller than the size of the main heading).
Screenshot 2019-10-03 at 1 53 59 AM
- [ ] This applies to your overall commit. There is very less space in between two lines. So the content doesn't look visually appealing. To do so, you can add your lines in separate `<Body1>` component and adjust their distance by using mt/mb classNames.

**Comment by ac030540** [comment]
- [ ] Also change the topic from Adhoc to Adhoc, Math

**Comment by Ckpuna4** [comment]
@ac030540 yes, I'll fix it.
But I can't test it on my local machine :( How can I do this? mb node version need or smthng else I do wrong

npm i
npm build / start 

@import "@material/card/mdc-card";
^
      File to import not found or unreadable: @material/card/mdc-card.
      in /Users/Ckpuna4/projects/Arena-2.0/node_modules/@material/react-card/index.scss (line 23, column 1)

**Comment by Ckpuna4** [comment]
oh.. my bad. forget about 
export SASS_PATH=./node_modules
:)
today I'll fix)

**Comment by Ckpuna4** [comment]
@ac030540 
Hi! All fixed in 
472edac

**Pull request merged**
