### PR TITLE
Added the route for resetting the problem status

### PR DESCRIPTION
**Pull request by ac030540**
I have made the following changes:

- [x] changed the `/developers` route to `our-team` route and accordingly changed the folder structure.

- [x] Added a new route. It can be viewed on `http://localhost:3000/admin/:contestId/reset/:problemId`.

### CODE REVIEW

**Comment by Swap76** [comment]
@ac030540 should we create an issue may be @Mithil467  will help you with that about updating the info of our-team page

**Comment by ac030540** [comment]
> @ac030540 should we create an issue may be @Mithil467 will help you with that about updating the info of our-team page

I didn't get you.

**Comment by ac030540** [comment]
> @ac030540 Great work the Page is super cool
> 
> Just the Update button is getting super close
> 
> Screenshot 2019-11-08 at 2 49 49 PM

Sure. I will fix that.

**Comment by Swap76** [comment]
> > @ac030540 should we create an issue may be @Mithil467 will help you with that about updating the info of our-team page
> 
> I didn't get you.

Our team page doesn’t have suriya, shabrish, devin So we can create issue for that @Mithil467 can work on that I think

**Comment by ac030540** [comment]
> > > @ac030540 should we create an issue may be @Mithil467 will help you with that about updating the info of our-team page
> > 
> > 
> > I didn't get you.
> 
> Our team page doesn’t have suriya, shabrish, devin So we can create issue for that @Mithil467 can work on that I think
Sure.

**Comment by ac030540** [comment]
> Clicking on Status and then changing the status is supposed to change the status? If so, then it is not working for me. Accepted statuses remain accepted.

You mean after refreshing? The status gets reset?

**Comment by Mithil467** [comment]
> You mean after refreshing? The status gets reset?

No. Just clicking on status drop-down. Then Wrong Answer. This doesn't change anything.

**Comment by ac030540** [comment]
> > You mean after refreshing? The status gets reset?
> 
> No. Just clicking on status drop-down. Then Wrong Answer. This doesn't change anything.

Okay. I will check why this is happening.

**Comment by ac030540** [comment]
> Clicking on Status and then changing the status is supposed to change the status? If so, then it is not working for me. Accepted statuses remain accepted.



> Good job with the developers to our-team change. Just one minor thing, would be nice if you change the line no. 14 in README.md. From developers to our-team.

Done

**Pull request merged**
