### PR TITLE
Updated apollo graphql, react-scripts & depreciated babel-parser

### PR DESCRIPTION
**Pull request by ac030540**
## Description of the change
- Updated the version of apollo graphql
- Updated the version of react-scripts
- Updated eslint config

## Type Of Change
- Breaking Change (fix or feature that would cause existing functionality to not work as expected)

## Development & Code Review

- [x] Fixed all the formatting errors (run `npm run format`)
- [x] The code changed/added has been covered with tests
- [x] All the test cases added/changed are passing

### CODE REVIEW

**Comment by ac030540** [comment]
@SalmanAd01 there can be breaking changes so please check it & let me know if there are any issues. I have tested caching, queries & mutations of graphql.

**Comment by SalmanAd01** [comment]
> @SalmanAd01 there can be breaking changes so please check it & let me know if there are any issues. I have tested caching, queries & mutations of graphql.

i check its is working fine but initially i got the prettier/prettier cr error which i solve by adding .editorconfig or we can set   
[rule](https://github.com/siesgstarena/Arena-2.0/blob/apollo-update/.eslintrc.js#L15)  
'prettier/prettier': [
      'error',
      {
        endOfLine: 'auto',
      },
    ],

**Review by SalmanAd01 — CHANGES_REQUESTED** [review]
I check its is working fine but initially i got the prettier/prettier cr error which i solve by adding .editorconfig or we can set
[rule](https://github.com/siesgstarena/Arena-2.0/blob/apollo-update/.eslintrc.js#L15)
'prettier/prettier': [
'error',
{
endOfLine: 'auto',
},
],

**Comment by ac030540** [comment]
@SalmanAd01 Not sure how you got that because I never faced that issue & I'm not able to reproduce either. Maybe your project is using the global version of eslint in the app as compared to the version specified in the project? On my machine, I don't have eslint installed globally.

**Comment by SalmanAd01** [comment]
> @SalmanAd01 Not sure how you got that because I never faced that issue & I'm not able to reproduce either. Maybe your project is using the global version of eslint in the app as compared to the version specified in the project? On my machine, I don't have eslint installed globally.

actually i'm on windows

**Comment by ac030540** [comment]
> > @SalmanAd01 Not sure how you got that because I never faced that issue & I'm not able to reproduce either. Maybe your project is using the global version of eslint in the app as compared to the version specified in the project? On my machine, I don't have eslint installed globally.
> 
> actually i'm on windows

Gotcha! I have added the endOfLine key in the .prettierrc file, please verify if it resolves the issue.

**Comment by SalmanAd01** [comment]
> > > @SalmanAd01 Not sure how you got that because I never faced that issue & I'm not able to reproduce either. Maybe your project is using the global version of eslint in the app as compared to the version specified in the project? On my machine, I don't have eslint installed globally.
> > 
> > 
> > actually i'm on windows
> 
> Gotcha! I have added the endOfLine key in the .prettierrc file, please verify if it resolves the issue.

LGTM

**Review by SalmanAd01 — APPROVED** [review]
This is looking good

**Pull request merged**
