### PR TITLE
Added basic homepage UI, learn UI and solved date issues.

### PR DESCRIPTION
**Pull request by ac030540**
## Description of the change
i. Added the homepage UI.
ii. Added the basic layout for learn page.
iii. Solved all the date time related issues.
iv. Removed all the custom functions for converting date and time and replaced them with date fns.

## Type Of Change

- [x] Bug Fix (non-breaking change that fixes an issue)
- [x] New Feature (non-breaking change that adds functionality)
- [ ] Breaking Change (fix or feature that would cause existing functionality to not work as expected)

## Development & Code Review

- [x] Fixed all the formatting errors (run `npm run format`)
- [x] The code changed/added has been covered with tests
- [x] All the test cases added/changed are passing

### CODE REVIEW

**Review by Swap76 — APPROVED** [review]
@ac030540 @greykoalacode Works perfect looks good also but is't it too much information given to the user 🤔

**Comment by ac030540** [comment]
> @ac030540 @greykoalacode Works perfect looks good also but is't it too much information given to the user 🤔

At which UI?

**Comment by Swap76** [comment]
> > @ac030540 @greykoalacode Works perfect looks good also but is't it too much information given to the user 🤔
> 
> At which UI?

The main page

**Review by greykoalacode — APPROVED** [review]
LGTM ! Happy to see efforts come real !

**Pull request merged**
