### PR TITLE
I have added the Scoreboard part of Contests component, check it out.

### PR DESCRIPTION
**Pull request by greykoalacode**
Thank you for contributing to Arena-2.0. Before pressing the "Create Pull Request" button, please provide the following:

- [x] A description about what and why you are contributing, even if it's trivial.

- [x] The issue number(s) or PR number(s) in the description if you are contributing in response to those.

- [x] If applicable, unit tests.

### CODE REVIEW

**Comment by greykoalacode** [comment]
I have made one change in package.json. According to CRA, [https://create-react-app.dev/docs/running-tests/#on-your-own-environment](I referred this) for testing in windows and apart from that, created Route for the Scoreboard component.

**Comment by ac030540** [comment]
Also make sure that you write descriptive commit messages. It is very important for a commit message to explain, "What changes you have made?" and "Why?".

**Comment by greykoalacode** [comment]
After you suggested the above changes, 

- In the package.json the test: default script has been added
- In the App.jsx , the name has been changed to Scoreboard
- In the DataTable.jsx and Data.js, comments have been added considering, more understandability and helpfulness. 
-Reference for the Table was taken from the status Table already made. 
- I hope I have got most of the things covered and if any more suggestions/improvisations, please let me know

**Comment by greykoalacode** [comment]
Hey,
- I have changed the naming of Data.js into data.js and changed its occurrences wherever seemed necessary.
- I have assigned a key prop to the map functions so that no console error is caught
- Thank you for suggesting these changes, do let me know if any more changes needed.

**Pull request merged**
